### PR TITLE
Update to newest LittleTiles version pre199

### PR DESCRIPTION
**Pull request by CreativeMD**
Hey there,
I have done some clean up and it breaks some compatibility with other mods. Might not be the best timing, but here is a fix.

The version of LittleTiles has not been released yet, but will be very soon.

In Regards
CreativeMD

### CODE REVIEW

**Comment by OreCruncher** [comment]
Just wanted you to know that I am aware of this PR.  Right now I am working on my 1.14.4 port and once I have that BETA published I will be back looking at 1.12.2 related things.

**Comment by CreativeMD** [comment]
No problem, but it would be good to know if it's about days, weeks or months?

**Comment by CreativeMD** [comment]
Or you do it right away :D

Just let me know if you release because then I have to release my version as well.

**Comment by OreCruncher** [comment]
Is this the only tweak you anticipate needing?

**Comment by CreativeMD** [comment]
Yeah, that should fix the issue.

**Comment by CreativeMD** [comment]
Nice! (Saw you uploaded a new version yesterday)

**Pull request merged**
